# Basic application properties
spring.application.name=jobshield
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jobshield
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata