# Basic application properties
spring.application.name=jobshield
server.port=8080

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# JWT
#jwt.secret=${JWT_SECRET}
jwt.secret=J8vK2mQ9xL4pR7sT1wY6nC3dF5hG8jN2kM7zP4qX9vB6sL1
jwt.expiration=${JWT_EXPIRATION:86400000}